spring:
  application:
    name: api-gateway
  jackson:
    deserialization:
      read-unknown-enum-values-as-null: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  flyway:
    locations: classpath:db/migration

logging:
  level:
    root: DEBUG

feign:
  user-service:
    name: userService
    url: http://localhost:3000

key:
  private: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCM73X8oze0mwSslclaSPkQd+2QDaNLwho6n4osPv7v0tYhtoevr6EoOHe3MQw/kt4zEV+2WP+BpNkTPFT8VMLb7bRiyVOM7pkMiPUAA9GSwqWLjt9Jxwn2oivnNjqQGiTg8oaccA92TsQtUQGwahP3tpXCnNW1kzaqDLUs8+DXQl/oMAHTWS0OMTz7WHcRTZ8tyJ9LHF5Xuk21YoOZzzBJ29IosphjLJcB7JmiSBDZrq5ZFpssNeMGbHjNRygKh5+aKrf0fXWOm4/ufgUr7j1ZNB2Qf1ffFOTK+SDEsutr3FQLcoTa8DffU3BBv2DhmsfgksMcnawM9T79diZDP4NrAgMBAAECggEAD2kHn65BIxBoPG7Ma4DbKv/SDBRRrLD2qT5Un23r9lE5dMo+n+k2V+2EuZU1X6Yxgaf+rTOiDIz353CLYmPqQp4FQV/+MMTOG17GW1APlFqQO2hN5gVLg5pL7qYxVRxmt+oM6gIezrLiJIpdAus2b7mZOoRnockNCx8EmHu6NA80jrEIAsclN8N05IOlqPjzCVAtY4NKvrk3ueKFjasi+898TQK4c4YxUT4C8r7WGzSw7P3/dTLoywJgB7/718OpEhk7b4wNhIPExwx4e+NInfce08pmpvENmYL6nUkzetrCqz+UJRgdnZfxdJv0s6nTucaTBex+3QIkRwwqBR+U4QKBgQD/A7Yx7y/VOV81Ye35DbpyMZUXtWE/iiLcsOSaWb5L+RaFSHgHv7tqJCtW+ElX0WanxKUKAHE7PG0V8CGaMBz0JCWUETJl99WUyNKeyCf9IScnAROUCEgFEibSYt5+yD0EPIc1vKLo4vF0HhBpvap7ZtgaHc315Ro/egNIP06tiQKBgQCNeuO+wBwyXB6rpWZp1+Xpq9mNBqqtjoD9lrzy45ZDTuVyudMOKivEyTOkhX4VxWCHIIVp5yoc0xntinrzGs89S8h/Ph9eKXuOlnEvpbrNEh7wmPOAV/1ePLHdMsB2fz8Wb0/uI4InsxekGFgbzpw5xSsFJWknojX6QVfSUsNAUwKBgDHbeuqGVfa9EcUxEUKpEXO0B+8rsginLCuzle4rb44Q8/s48Oaq8KxOx/5n6ob11LkmNBIhhgHLzZQFb7xifbapvoMVXaIb8zD0lmEextqxeaMhjb9aYyJCqz5kwBVPdsZ2QwUZjUw02noWSqUxxLv9nnB0tUjG8vvIEg40+l/pAoGAByo9FHD4PJiruPekayHS8/WPC/RVenqoD6+tnANonboGJrxAcwwxsUKbSe60xvd6/vznpMhfOpx6SKxls6Ac9La8zazgu80QA9Wcn9Qd1LrhNEAavNo366jZPSGP27BwCnvSqXXE5qvMO7Q76hSZltdkaVtOqwItB6J9hxpH5x8CgYBP3OO8UuJpLoFZ2FfSnrsY0aO9eiJjmHq8rSCe0lKR+/IGPC1Wc+x+NtA/SbEit0R/5LKJ5A+RVvGAuUyVmcrJUgcSgueHupdp9lGY4OhhG8Qn2+Us8HZdOG+dwn/D+eC9xZt7E3w8zhuZv3OhOy/U6WR2gKYPuk5QJMeBt5FUHw==
  public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjO91/KM3tJsErJXJWkj5EHftkA2jS8IaOp+KLD7+79LWIbaHr6+hKDh3tzEMP5LeMxFftlj/gaTZEzxU/FTC2+20YslTjO6ZDIj1AAPRksKli47fSccJ9qIr5zY6kBok4PKGnHAPdk7ELVEBsGoT97aVwpzVtZM2qgy1LPPg10Jf6DAB01ktDjE8+1h3EU2fLcifSxxeV7pNtWKDmc8wSdvSKLKYYyyXAeyZokgQ2a6uWRabLDXjBmx4zUcoCoefmiq39H11jpuP7n4FK+49WTQdkH9X3xTkyvkgxLLra9xUC3KE2vA331NwQb9g4ZrH4JLDHJ2sDPU+/XYmQz+DawIDAQAB
